// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaAlquilerDeComputadoras.Data;

#nullable disable

namespace SistemaAlquilerDeComputadoras.Migrations
{
    [DbContext(typeof(SistemaAlquilerDeComputadorasContext))]
    [Migration("20240702192622_CreacionFlete")]
    partial class CreacionFlete
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);



            modelBuilder.Entity("SistemaAlquilerDeComputadoras.Models.Equipo", b =>
                {
                    b.Property<string>("Codigo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Almacenamiento")
                        .HasColumnType("int");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<string>("Foto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pantalla")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Procesador")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Ram")
                        .HasColumnType("int");

                    b.Property<string>("Resolucion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Codigo");

                    b.ToTable("Equipo");
                });

            modelBuilder.Entity("SistemaAlquilerDeComputadoras.Models.Flete", b =>
                {
                    b.Property<int>("NroRecibo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");



                    b.Property<decimal>("Costo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("HoraFinal")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("HoraInicio")
                        .HasColumnType("datetime2");

                    b.HasKey("NroRecibo");

                    b.ToTable("Flete");
                });
#pragma warning restore 612, 618
        }
    }
}
