// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaAlquilerDeComputadoras.Contexto;

#nullable disable

namespace SistemaAlquilerDeComputadoras.Migrations
{
    [DbContext(typeof(MyContext))]
    partial class MyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("SistemaAlquilerDeComputadoras.Models.Cliente", b =>
                {
                    b.Property<int>("Ci")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NombreCompleto")
                        .HasColumnType("TEXT");

                    b.HasKey("Ci");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("SistemaAlquilerDeComputadoras.Models.Equipo", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Almacenamiento")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Foto")
                        .HasColumnType("TEXT");

                    b.Property<string>("Pantalla")
                        .HasColumnType("TEXT");

                    b.Property<string>("Procesador")
                        .HasColumnType("TEXT");

                    b.Property<int>("Ram")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Resolucion")
                        .HasColumnType("TEXT");

                    b.HasKey("Codigo");

                    b.ToTable("Equipos");
                });

            modelBuilder.Entity("SistemaAlquilerDeComputadoras.Models.Flete", b =>
                {
                    b.Property<int>("NroRecibo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Costo")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("EquipoId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("HoraFinal")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("HoraInicio")
                        .HasColumnType("TEXT");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("NroRecibo");

                    b.HasIndex("EquipoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Fletes");
                });

            modelBuilder.Entity("SistemaAlquilerDeComputadoras.Models.Usuario", b =>
                {
                    b.Property<int>("Ci")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cuenta")
                        .HasColumnType("TEXT");

                    b.Property<int>("Edad")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NombreCompleto")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<int>("Rol")
                        .HasColumnType("INTEGER");

                    b.HasKey("Ci");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("SistemaAlquilerDeComputadoras.Models.Flete", b =>
                {
                    b.HasOne("SistemaAlquilerDeComputadoras.Models.Equipo", "Equipo")
                        .WithMany("Fletes")
                        .HasForeignKey("EquipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaAlquilerDeComputadoras.Models.Usuario", "Usuario")
                        .WithMany("Fletes")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SistemaAlquilerDeComputadoras.Models.Equipo", b =>
                {
                    b.Navigation("Fletes");
                });

            modelBuilder.Entity("SistemaAlquilerDeComputadoras.Models.Usuario", b =>
                {
                    b.Navigation("Fletes");
                });
#pragma warning restore 612, 618
        }
    }
}
